[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "3D Lore"
authors = [{name = "Joe Moore", email = "jo3moore@gamil.com"}]
dynamic = ["version", "description"]
